#!/bin/bash
# =============================================================================
# app-leftover-search.sh
#
# Searches common macOS locations for leftover files from a deleted application.
# Performs a case-insensitive search for the app name. If the name contains
# spaces, also searches for hyphenated and underscored variants
# (e.g., "Good Notes" also matches good-notes and good_notes).
#
# Usage:
#   ./app-leftover-search.sh "AppName"
#
# Shortcuts setup:
#   1. Add an "Ask for Input" action (type: Text) — prompt: "App name to search for"
#   2. Add a "Run Shell Script" action
#      - Shell: /bin/bash
#      - Input: Shortcut Input
#      - Pass Input: as arguments
#      - Paste this entire script
# =============================================================================

app_name="${1:-}"

if [ -z "$app_name" ]; then
    osascript -e 'display dialog "No app name was provided." buttons {"OK"} default button "OK" with icon stop'
    exit 1
fi

safe_name="$(echo "$app_name" | sed 's/ /-/g')"
output_file="$HOME/Desktop/${safe_name}-extras.txt"
tmp_results="$(mktemp /tmp/app-leftover-search.XXXXXX)"

trap 'rm -f "$tmp_results"' EXIT

# -----------------------------------------------------------------------------
# search_location DIR DESCRIPTION [DEPTH]
#   Searches DIR (case-insensitive) for files/folders whose name contains the
#   app name (and hyphenated/underscored variants if the name has spaces).
#   Results are appended to tmp_results as tab-separated "path<TAB>description"
#   lines.
# -----------------------------------------------------------------------------
search_location() {
    local dir="$1"
    local description="$2"
    local depth="${3:-1}"

    [ -d "$dir" ] || return 0

    local name_expr=(-iname "*${app_name}*")

    if [[ "$app_name" == *" "* ]]; then
        local hyphenated="${app_name// /-}"
        local underscored="${app_name// /_}"
        name_expr=(\( -iname "*${app_name}*" -o -iname "*${hyphenated}*" -o -iname "*${underscored}*" \))
    fi

    find "$dir" -maxdepth "$depth" "${name_expr[@]}" 2>/dev/null || true \
    | while IFS= read -r match; do
        printf '%s\t%s\n' "$match" "$description"
    done >> "$tmp_results"
}

# ========================== User Library ======================================

search_location "$HOME/Library/Application Support" \
    "App data and configuration files" 2

search_location "$HOME/Library/Caches" \
    "Cached data — temporary files stored by the app" 2

search_location "$HOME/Library/Preferences" \
    "Preference file — app settings and configuration (plist)"

search_location "$HOME/Library/Preferences/ByHost" \
    "Host-specific preference file"

search_location "$HOME/Library/LaunchAgents" \
    "User launch agent — background process definition"

search_location "$HOME/Library/Logs" \
    "Log files generated by the app" 2

search_location "$HOME/Library/Saved Application State" \
    "Saved window and session state data"

search_location "$HOME/Library/Containers" \
    "Sandboxed app container — data, preferences, and caches" 2

search_location "$HOME/Library/Group Containers" \
    "Shared app group container — data shared between extensions" 2

search_location "$HOME/Library/HTTPStorages" \
    "HTTP cookie and storage data"

search_location "$HOME/Library/Cookies" \
    "Browser or app cookie files"

search_location "$HOME/Library/Application Scripts" \
    "Automation scripts registered by the app" 2

search_location "$HOME/Library/PreferencePanes" \
    "System Settings preference pane"

search_location "$HOME/Library/Internet Plug-Ins" \
    "Internet or browser plug-in"

search_location "$HOME/Library/Input Methods" \
    "Custom input method or keyboard extension"

search_location "$HOME/Library/Screen Savers" \
    "Screen saver module"

search_location "$HOME/Library/Services" \
    "macOS Services menu workflow"

search_location "$HOME/Library/Spotlight" \
    "Spotlight importer plug-in"

search_location "$HOME/Library/WebKit" \
    "WebKit local storage and browsing data" 2

# ========================== System Library ====================================

search_location "/Library/Application Support" \
    "System-wide app data and configuration" 2

search_location "/Library/Caches" \
    "System-wide cached data" 2

search_location "/Library/Preferences" \
    "System-wide preference file"

search_location "/Library/LaunchAgents" \
    "System launch agent — background process for all users"

search_location "/Library/LaunchDaemons" \
    "System launch daemon — root-level background service"

search_location "/Library/Logs" \
    "System-wide log files" 2

search_location "/Library/PrivilegedHelperTools" \
    "Privileged helper tool — runs with elevated permissions"

search_location "/Library/StartupItems" \
    "Legacy startup item"

search_location "/Library/PreferencePanes" \
    "System-wide preference pane"

search_location "/Library/Internet Plug-Ins" \
    "System-wide internet plug-in"

search_location "/Library/Input Methods" \
    "System-wide input method"

search_location "/Library/Screen Savers" \
    "System-wide screen saver"

search_location "/Library/Extensions" \
    "System extension or kernel extension"

search_location "/Library/Frameworks" \
    "Application framework bundle"

# ========================== Applications ======================================

search_location "/Applications" \
    "Application bundle — may not have been fully removed"

search_location "$HOME/Applications" \
    "User-installed application bundle"

search_location "/Applications/Utilities" \
    "Utility application"

# ========================== Homebrew (Intel) ==================================

search_location "/usr/local/bin" \
    "CLI tool or symlink installed by the app"

search_location "/usr/local/sbin" \
    "System CLI tool installed by the app"

search_location "/usr/local/etc" \
    "Configuration file installed by the app" 2

search_location "/usr/local/var" \
    "Variable data — logs, databases, or runtime files" 2

search_location "/usr/local/opt" \
    "Homebrew-linked formula or dependency"

search_location "/usr/local/Caskroom" \
    "Homebrew Cask staging files"

search_location "/usr/local/Cellar" \
    "Homebrew formula installation"

# ========================== Homebrew (Apple Silicon) ==========================

search_location "/opt/homebrew/bin" \
    "CLI tool or symlink (Apple Silicon Homebrew)"

search_location "/opt/homebrew/sbin" \
    "System CLI tool (Apple Silicon Homebrew)"

search_location "/opt/homebrew/etc" \
    "Configuration file (Apple Silicon Homebrew)" 2

search_location "/opt/homebrew/var" \
    "Variable data (Apple Silicon Homebrew)" 2

search_location "/opt/homebrew/opt" \
    "Homebrew-linked formula (Apple Silicon)"

search_location "/opt/homebrew/Caskroom" \
    "Homebrew Cask staging files (Apple Silicon)"

search_location "/opt/homebrew/Cellar" \
    "Homebrew formula installation (Apple Silicon)"

# ========================== System Receipts & Temp ============================

search_location "/private/var/db/receipts" \
    "Installer package receipt — record of a .pkg installation"

search_location "/private/tmp" \
    "Temporary files left in system temp directory"

# ==============================================================================
# Build the output file
# ==============================================================================

count="$(cut -f1 "$tmp_results" | sort -u | wc -l | tr -d ' ')"

if [ "$count" -eq 0 ]; then
    osascript -e "display dialog \"No leftover files found for \\\"${app_name}\\\".\" buttons {\"OK\"} default button \"OK\" with icon note"
    exit 0
fi

{
    echo "Leftover files found for \"${app_name}\""
    echo "Searched on $(date '+%Y-%m-%d at %H:%M')"
    echo "==========================================="
    echo ""

    sort -t$'\t' -k1,1 -u "$tmp_results" | while IFS=$'\t' read -r path description; do
        echo "$path"
        echo "  $description"
        echo ""
    done

    echo "---"
    echo "${count} item(s) found."
    echo ""
    echo "Review each path before deleting. Some files may belong to"
    echo "other apps with similar names or shared dependencies."
} > "$output_file"

open -a "TextEdit" "$output_file"
